---

is_debug: true
jwt:
  secret: $3cr3t
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10000
category_service:
  url: http://127.0.0.1:5000/api
note_service:
  url: http://ns-note_service:10003/api
user_service:
  url: http://127.0.0.1:5000/api
tag_service:
  url: http://ns-tag_service:10004/api